### PR TITLE
Add idempotency for PersistentQueue collection type

### PR DESCRIPTION
**Pull request by StephenRudolph**
This pull request would add support for the `PersistentQueue` collection type, so that transformations on that type result in collections of the same type. Previously, `PersistentQueue`s were treated with special behavior particular to lists, which are LIFO (last in first out) stacks, unlike queue which are FIFO (first in first out). This change was first discussed in #60. A unit test has also been added to check idempotency for transformations on vectors, sets, lists, maps, and queues.

This was my first venture into ClojureScript code - I think there may be ClojureScript-specific issues unrelated to my work. The unit test I created fails for both sets and queues because they do not implement an apparently required interface:
```
Error: No protocol method IReduce.-reduce defined for type cljs.core/PersistentQueue: #queue []
Error: No protocol method IReduce.-reduce defined for type cljs.core/PersistentHashSet: #{}
```

I welcome any feedback!

### CODE REVIEW

**Comment by nathanmarz** [comment]
ClojureScript doesn't implement clojure.core.reducers for many datatypes. We'll either have to implement that protocol ourselves or provide an alternate implementation for CLJS. This is related to #53

**Comment by StephenRudolph** [comment]
I looked around the ClojureScript project and couldn't find anything regarding whether or not they intended to implement reducers for those types at some point. Before attempting to implement something specific for this project, I went ahead and reached out to see if having those reducers defined would fit with their own goals: https://groups.google.com/forum/#!topic/clojurescript/h-EYTTndvAY.

**Comment by nathanmarz** [comment]
We actually already talked about this with the ClojureScript devs – they are not planning to support reducers because I believe transducers are favored moving forward. The reason Specter doesn't use transducers is for Clojure 1.6 compatibility – but I'd be all in favor of having a ClojureScript-specific version of ALL that uses transducers.

**Comment by StephenRudolph** [comment]
I'll give it a shot then!

**Comment by StephenRudolph** [comment]
It turned out to be easier than I expected - using transducers also seems to clean up the code a bit as well. I added a flag so the reducers library is no longer required for CLJS.

**Comment by nathanmarz** [comment]
Sorry I'm really late on this – I've been consumed by a really difficult project but now that's behind me.

This looks really good. Before I merge this in, I think I will need a contributor agreement signed. It's annoying but really important to keep the project on a sound legal foundation. I'll put that together in the next couple of days and then send you a link to it.

**Comment by StephenRudolph** [comment]
Not a problem! I'll be happy to sign whatever you come up with. Thanks!

**Comment by nathanmarz** [comment]
OK, I just need your email address to send the document to e-sign. Can you email me at nathan@nathanmarz.com?

**Comment by nathanmarz** [comment]
Great work and thanks for the patience! Eliminating the usage of reducers relieves a major problem with the cljs version. FYI, I made a couple of minor refactorings: https://github.com/nathanmarz/specter/commit/0134656d0a78d5b5c92efa0bbbb53835984cfa82

**Comment by StephenRudolph** [comment]
I'm glad I could contribute! 👍

**Pull request merged**
