### PR TITLE
Add dates to all changelog entries

### PR DESCRIPTION
**Pull request by DjebbZ**
Notes: 
- Not all versions appear in git tags --list nor in the releases pages. Had to walk the log to find a few missing ones.
- I followed the date format ISO 8601 as recommended by keepachangelog.com v1.0.0 (latest to date).

### CODE REVIEW

**Comment by DjebbZ** [comment]
This PR fixes #243

**Comment by nathanmarz** [comment]
The best way to check a release date is to look on Clojars. I noticed that the dates here for 1.1.0 and 0.7.0 are off:

https://clojars.org/com.rpl/specter/versions/1.1.0
https://clojars.org/com.rpl/specter/versions/0.7.0

**Comment by nathanmarz** [comment]
Looks like the 1.1.0 date is still off.

**Comment by DjebbZ** [comment]
Indeed, international format haha... I fixed and squashed all commits into one to avoid polluting the history.

**Comment by nathanmarz** [comment]
Thanks!

**Comment by DjebbZ** [comment]
You're welcome!

**Pull request merged**
